### ISSUE TITLE
Support for external mailboxes?

### ISSUE THREAD

**Issue by e-alfred** [nextcloud/files_frommail#1]
Hello,

is it possible to use this with an external mailbox as well? Or do I have to set up for example fetchmail and execute the PHP script afterwards?

**Comment by daita** [comment]
What do you mean by external mailbox ?

**Comment by e-alfred** [comment]
A mailbox from a provider where I do not have direct access to the mail server configuration, only to the mailbox itself. Even if I had access to the the mail server directly it might be impossible to set up the app because it is not possible to set up what the app needs (for example with Exchange or other mail server software).

**Comment by daita** [comment]
Ok, so this feature is more something that should be added to the Mail App.

This is already covered by: https://github.com/nextcloud/files_frommail/issues/3

**Comment by e-alfred** [comment]
No, not really. I still would like a mail account where files are automatically moved into a folder on Nextcloud, but where mail server access to set up a script and change the configuration is not possible. 

This mail account shouldn't be necessarily set up for a certain user like it is done with the mail app for example. Also, the Mail app doesn't do automatic attachment saving (should be done when logged out as well) which would make up for the feature this app provides.

**Comment by daita** [comment]
I mean, the only way to fix both of this issue is to integrate a similar feature to the Mail App.
That feature would check your mailbox from time to time for new mails (can also be run when you receive mails in the webclient) and directly save their attachments locally. 

Files_FromMail is just parsing mails and will never be a mail client.

**Comment by xXSTrikeXx** [comment]
@daita 
My request is not directly about external mailproviders. But please check this thread: https://help.nextcloud.com/t/paperless-home-letters-bills/27819
Since you are involved in fulltextsearch and this addon, maybe my thread can inspire you for the future.
Thanks for the effort and this work!

**Comment by p3pp0** [comment]
is there any update on this? 
I would love to use a external hosted mail server with this script
